//./jshttp(改).js
{
//"spider":"./top98_1.jar",
"sites" : [
{"key":"drpy","name":"豆瓣🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"农民","name":"💬評分 農民","type":3,"api":"./lib/drpy2.min.js","ext":"./js/农民影视.js"},
{"key":"一起看","name":"💬評分/集數 一起看","type":"3","api":"csp_Dora","changeable":"0","searchable":"1","quickSearch":"1","filterable":"1","ext":"8e3aefcba838d8dc5102ac786719d837","jar":"./t.jar"},
{"key":"起飞影院網","name":"💬評分 起飞影院","type":3,"api":"./lib/drpy2.min.js","ext":"./js/起飞影院.js"},
{"key":"乐鱼影视","name":"💬集數 乐鱼影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/乐鱼影视.js"},
{"key":"MGT","name":"🥭芒果(官)","type":3,"api":"csp_Mtv","searchable":1,"quickSearch":1,"filterable":1,"jar":"./xm.jar"},
{"key":"SPIQY","name":"🥝愛奇藝(SP)","type":3,"api":"csp_Itv","searchable":1,"quickSearch":1,"filterable":1,"jar":"./xm.jar"},
{"key":"SPQQ","name":"🐧腾讯(官)","type":3,"api":"csp_Qtv","searchable":0,"quickSearch":0,"filterable":0,"jar":"./xm.jar"},
{"key":"drpy_js_百忙无果","name":"官源🏛芒果🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/百忙无果.js"},
{"key":"drpy_js_奇珍异兽","name":"官源🏛爱奇艺🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇珍异兽.js"},
{"key":"drpy_js_腾云驾雾","name":"官源🏛腾讯🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/腾云驾雾.js"},
//{"key":"豆瓣","name":"豆瓣2🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy_js_豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/drpy2.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/drpy.js"},
{"key":"欧乐影院","name":"🛩歐樂影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/欧乐影院(改).js"},
{"key":"独播库","name":"🛩独播库🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/独播库.js"},
{"key":"欧帝影院","name":"🛩欧帝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧帝影院.js"},
{"key":"優質资源网","name":"🏆優質资源1080","type":0,"api":"https://api.1080zyku.com/inc/api.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"量子资源網","name":"🏆量子资源lz","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"categories":["国产剧","国产动漫","泰国剧","台湾剧","香港剧","欧美剧","韩国剧","日本剧","动漫","体育","剧情片","动作片","爱情片","喜剧片"]},
{"key":"淘片资源网","name":"🏆淘片资源tp","type":0,"api":"https://taopianapi.com/home/cjapi/as/mc/vod/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"非凡资源网","name":"🏆非凡资源ff","type":0,"api":"http://cj.ffzyapi.com/api.php/provide/vod/from/ffm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"天空资源网","name":"🏆天空资源网tk","type":0,"api":"https://api.tiankongapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快车资源網","name":"🌟快车资源kc","type":1,"api":"https://caiji.kczyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"飛速资源网","name":"🌟飛速资源fe","type":0,"api":"https://www.feisuzyapi.com/api.php/provide/vod/from/fsm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快播资源網","name":"🌟快播资源kb","type":1,"api":"http://www.kuaibozy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"樱花资源網","name":"🌟樱花资源yh","type":1,"api":"https://m3u8.apiyhzy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"68资源网","name":"🌟68资源68","type":0,"api":"https://caiji.68zyapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"if101","name":"🌟if101","type":3,"api":"./lib/drpy2.min.js","ext":"./js/if101.js"},
{"key":"CK资源采集网","name":"🏆CK资源采集网","type":1,"api":"https://ckzy.me/api.php/provide/vod/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"CK资源(VPN)","name":"🛩CK资源(VPN)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/ck资源.js"},
{"key":"海外看资源网","name":"🏆海外看haiwaikan","type":0,"api":"https://haiwaikan.com/api.php/provide/vod/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"539影院","name":"💬539影院","type":3,"api":"./lib/drpy2.min.js","ext":"./js/539影院.js"},
{"key":"91free","name":"💬 集數 91free","type":3,"api":"./lib/drpy2.min.js","ext":"./js/91free.js"},
{"key":"酷影[V2]","name":"💬集數 酷影","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷影[V2].js"},
{"key":"gaze","name":"💬gaze🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/gaze.js"},
{"key":"八蛋影视","name":"💬八蛋影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/八蛋影视.js"},
{"key":"影渣渣","name":"💬影渣渣🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影渣渣.js"},
{"key":"尘落影视","name":"💬尘落影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/尘落影视.js"},
{"key":"追剧喵","name":"💬追剧喵🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧喵.js"},
{"key":"喵喵","name":"💬喵喵🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/喵喵(改).js"},
{"key":"菜狗","name":"💬菜狗🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/菜狗.js"},
{"key":"drpy_js_优酷","name":"官源🏛优酷🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/优酷.js"},
{"key":"多瑙影视","name":"🈵多瑙影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/多瑙影视(改).js"},
{"key":"小宝影视","name":"🈵☁小宝影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小宝影视.js"},
{"key":"回响影视","name":"🈵回响影视🔎評分","type":3,"api":"./lib/drpy2.min.js","ext":"./js/回响影视.js"},
{"key":"真不卡","name":"🈵☁真不卡🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/真不卡.js"},
{"key":"卧龙资源網","name":"🌕卧龙资源wolong","type":1,"api":"https://collect.wolongzyw.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"新浪资源","name":"🌕新浪资源xl","type":0,"api":"https://api.xinlangapi.com/xinlangapi.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"鱼乐资源網","name":"🌕鱼乐资源le","type":1,"api":"https://api.ylzy1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"U酷资源網","name":"🌕U酷资源uk","type":1,"api":"https://api.ukuapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鷹资源网","name":"🌕金鷹资源jyz","type":0,"api":"https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"红牛资源","name":"🌕红牛资源hn","type":0,"api":"https://www.hongniuzy2.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"drpy_js_360影视","name":"官源🏛360","type":3,"api":"./lib/drpy2.min.js","ext":"./js/360影视.js"},
//{"key":"drpy_js_菜狗","name":"官源🏛搜狗🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/菜狗.js"},
{"key":"7喜影院","name":"🛩7喜影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/7喜影院(改).js"},
{"key":"量子影视","name":"🛩量子影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/量子影视(改).js"},
{"key":"飞兔影视","name":"🛩飞兔影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/飞兔影视(改).js"},
//{"key":"艾旦影视資源網","name":"🌕艾旦影视","type":1,"api":"https://lovedan.net/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"百度资源网","name":"🌕百度资源db","type":0,"api":"https://api.apibdzy.com/api.php/provide/vod/from/dbm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"FOX资源","name":"😰FOX资源fox","type":1,"api":"https://api.foxzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"光速资源","name":"😰光速资源gs","type":0,"api":"https://api.guangsuapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"速影","name":"😰速影動漫wj","type":1,"api":"https://速影128.xyz/inc/apijson.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"闪电资源","name":"😰闪电资源sd","type":1,"api":"http://sdzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"酷点资源网","name":"😰酷点资源网kd","type":0,"api":" https://kudian10.com/api.php/provide/vod/from/kdm3u8/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"无尽资源网","name":"😰无尽资源wj","type":0,"api":"https://api.wujinapi.me/api.php/provide/vod/from/wjm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"阳光资源","name":"😰阳光资源","type":0,"api":"https://xxzy.org/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"海兔影院","name":"🛩海兔影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海兔影院.js"},
{"key":"小宝影院","name":"🛩小宝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小宝影院.js"},
{"key":"HoHo影视","name":"🛩HoHo影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HoHo影视.js"},
{"key":"唐人街影视","name":"🛩唐人街影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/唐人街影视.js"},
{"key":"爱壹帆","name":"🛩爱壹帆🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱壹帆.js"},
{"key":"大中影视","name":"🛩大中影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大中影视.js"},
{"key":"金曼影视","name":"🛩金曼影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/金曼影视.js"},
{"key":"泥巴","name":"🛩泥巴🔎","type":3,"api":"csp_Nbys","searchable":1,"filterable":1,"jar":"./top98_1.jar"},
{"key":"大米星球","name":"🌎大米星球(量)🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/大米星球(改).js"},
{"key":"奇优影院","name":"🌎奇优影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/奇优影院(改).js"},
{"key":"追剧啦","name":"🌎追剧啦(TK、CK)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/追剧啦(改).js"},
{"key":"天天视频","name":"🌎天天视频(CK)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/天天视频(改).js"},
{"key":"鸭奈飞","name":"🌎鸭奈飞🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/鸭奈飞.js"},
{"key":"歪片星球","name":"歪片星球🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/歪片星球.js"},
{"key":"奇珍异兽","name":"奇珍异兽🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇珍异兽.js"},
{"key":"NFM影视","name":"🌎NFM影视(量子🍭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/NFM影视.js"},
{"key":"艾旦影视","name":"🌎艾旦影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/艾旦影视(改).js"},
{"key":"HG影院[V2]","name":"🌎HG影院[V2](ff)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/HG影院[V2](改).js"},
{"key":"纽约影院","name":"🌎纽约影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/纽约影院(改).js"},
{"key":"朴樱影视","name":"朴樱影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/朴樱影视(改).js"},
{"key":"星空影视","name":"🌎星空影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/星空影视(改).js"},
{"key":"蛋蛋赞","name":"🌎蛋蛋赞🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/蛋蛋赞(改).js"},
{"key":"蛋蛋魔法","name":"🌎蛋蛋魔法🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/蛋蛋魔法(改).js"},
{"key":"追剧达人","name":"🌎追剧达人🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/追剧达人(改).js"},
{"key":"NY影院","name":"🧡NY影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/NY影院(改).js"},
{"key":"浮生半日","name":"🌎浮生半日🔎(TK)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/浮生半日(改).js"},
{"key":"子子影视","name":"子子影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/子子影视(改).js"},
{"key":"我爱跟剧","name":"我爱跟剧🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/我爱跟剧(改).js"},
{"key":"土狗影院","name":"土狗影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/土狗影院(改).js"},
{"key":"小狗影院","name":"小狗影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/小狗影院(改).js"},
{"key":"海外看影院","name":"海外看影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/海外看影院(改).js"},
{"key":"天空影视[V2]","name":"🌎天空影视[V2](ff)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/天空影视[V2].js"},
{"key":"555影视[V2]","name":"☁555影视[V2]🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/555影视[V2].js"},
{"key":"UrleBird","name":"🛤TikTok镜像","type":3,"api":"./lib/drpy2.min.js","ext":"./js/UrleBird.js"},
{"key":"JustLive","name":"🛤JustLive🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JustLive.js"},
{"key":"短视频","name":"🛤短视频","type":3,"api":"./lib/drpy2.min.js","ext":"./js/短视频.js"},
{"key":"斗鱼直播","name":"🛤斗鱼直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/斗鱼直播.js"},
{"key":"虎牙直播","name":"🛤虎牙直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/虎牙直播.js"},
{"key":"哔哩直播","name":"🛤哔哩直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩直播.js"},
{"key":"哔哩影视","name":"🛤哔哩影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩影视.js"},
{"key":"KUBO影视","name":"🇹🇼KUBO(繁體)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/KUBO影视.js"},
{"key":"映迷影院","name":"🇹🇼映迷(繁體)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/映迷影院.js"},
{"key":"剧迷","name":"🇹🇼剧迷(繁體)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/剧迷.js"},
{"key":"楓林網","name":"🇹🇼楓林網(繁體)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(改)/楓林網(改).js"},
{"key":"粤爱看","name":"🇭🇰粤爱看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/粤爱看.js"}
],
"lives": [
    {
      "name": "直播源",
      "type": 0,
      "url": "./直播源(1).txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },    
    {
      "name": "FongMi",
      "type": 1,
      "url": "https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/live.json",
      "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={epg}&date={date}",
      "logo": "http://epg.51zmt.top:8000/{logo}"
    },
    {
      "name": "台灣",
      "type": 0,
      "url": "./live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
        {
      "name": "直播1",
      "type": 0,
      "url": "http://home.jundie.top:81/Cat/tv/live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
    {
      "name": "直播2",
      "type": 0,
      "url": "https://dashu0754.com/api/v3/file/get/111/%E6%82%9F%E7%A9%BA.txt?sign=Vh_6WlBWzq1GeV88r1QjRQE9DCNcz5rBZpmSMo_q_y8%3D%3A0",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    }
  ],
"rules": [ 
{"host":"*", "rule":["douyinvod.com", "/video/tos/cn/"]}, 
{"host":"*", "rule":["default.365yg.com", "/video/tos/cn/"]}, 
{"host":"*","rule":["ysting.ysxs8.vip","m4a"]},
{"host":"*", "rule":["/m3u8.php?path=", ".m3u8"]}, 
{"host":"*", "rule":["/API.php?time=", "key=", "path=", ".m3u8"]}, 
{"host":"*", "rule":["oss-cn-m3u8", "myqcloud.com.zh188.net", "?url=", ".m3u8"]}, 
{"host":"*", "rule":["iesdouyin.com/aweme", "video_id="]},
{"host":"*", "rule":["douyin.com/aweme", "video_id="]},
{"host":"*", "rule":["huoshan.com", "/item/video/"]}, 
{"host":"*", "rule":["http((?!http).){12,}?\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)\\?.*"]}, 
{"host":"*", "rule":["http((?!http).){12,}\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)"]},
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".m3u8"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mp4"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mkv"]}, 
{"host":"www.007ts.me", "rule":["hls.pchj.net", ".m3u8"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time="]},
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},
{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},
{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]}
],
"parses":[
//{"name":"解析聚合","type":3,"url":"Demo"},
//{"name":"Web聚合","type":3,"url":"Web"},
{"name":"愛奇藝芒果","type":0,"url":"https://jx.zhanlangbu.com/?url="},
{"name":"優酷","type":1,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url="},
{"name":"騰訊","type":1,"url":"http://xn--wnup5g.xn--z7x900a.love:63/Art1/analysis.php?v=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"]}},
{"name":"3号线","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"4号线","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"5号线","type":0,"url":"https://jx.bozrc.com:4433/player/?url="},
{"name":"6号线","type":0,"url":"https://jx.parwix.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"7号线","type":0,"url":"https://jx.parwix.com:4433/player/analysis.php?v=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"8号线","type":0,"url":"https://h5.freejson.xyz/player/?url="},
{"name":"9号线","url":"https://www.8090g.cn/?url="},
{"name":"10号线","type":1,"url":"http://json.youguo520.top/fufeng/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"Dart/2.14(dart:io)"}}},
{"name":"11号线","type":1,"url":"https://jx.4kdv.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"12号线","type":0,"url":"https://jx.m3u8.tv/jiexi/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"13号线","type":0,"url":"https://www.ckmov.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"14号线","type":1,"url":"https://api.jiexi.la/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"15号线","type":0,"url":"https://www.nxflv.com/?url="},
{"name":"16号线","type":0,"url":"https://jx.jsonplayer.com/player/?url="},
{"name":"17号线","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"18号线","type":0,"url":"https://jx.ccabc.cc/byg/?url="},
{"name":"19号线","type":0,"url":"https://jx.zhanlangbu.com/?url=","ext":{"header":{"User-Agent":"okhttp/4.1.0"},"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"20号线","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"21号线","type":0,"url":"https://okjx.cc/?url="},
{"name":"22号线","type":0,"url":"http://jx.ivito.cn/?url="},
{"name":"23号线","type":0,"url":"https://dm.xbqgx.com/?url="},
{"name":"24号线","type":0,"url":"https://vip.bljiex.com/?v="},
{"name":"25号线","type":0,"url":"http://pandown.pro/app/ysmjx.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}}],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg",
    "ads": [
        "https://vip.ffzy",
        "https://vip.lz",
        "https://hd.lz",
       "vip.ffzyad.com",
        "iqiyi.hbuioo.com",
        "https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd",
        "mimg.0c1q0l.cn",
        "www.googletagmanager.com",
        "www.google-analytics.com",
        "mc.usihnbcq.cn",
        "mg.g1mm3d.cn",
        "mscs.svaeuzh.cn",
        "cnzz.hhttm.top",
        "tp.vinuxhome.com",
        "cnzz.mmstat.com",
        "www.baihuillq.com",
        "s23.cnzz.com",
        "z3.cnzz.com",
        "c.cnzz.com",
        "stj.v1vo.top",
        "z12.cnzz.com",
        "img.mosflower.cn",
        "tips.gamevvip.com",
        "ehwe.yhdtns.com",
        "xdn.cqqc3.com",
        "www.jixunkyy.cn",
        "sp.chemacid.cn",
        "hm.baidu.com",
        "s9.cnzz.com",
        "z6.cnzz.com",
        "um.cavuc.com",
        "mav.mavuz.com",
        "wofwk.aoidf3.com",
        "z5.cnzz.com",
        "xc.hubeijieshikj.cn",
        "tj.tianwenhu.com",
        "xg.gars57.cn",
        "k.jinxiuzhilv.com",
        "cdn.bootcss.com",
        "ppl.xunzhuo123.com",
        "xomk.jiangjunmh.top",
        "img.xunzhuo123.com",
        "z1.cnzz.com",
        "s13.cnzz.com",
        "xg.huataisangao.cn",
        "z7.cnzz.com",
        "xg.huataisangao.cn",
        "z2.cnzz.com",
        "s96.cnzz.com",
        "q11.cnzz.com",
        "thy.dacedsfa.cn",
        "xg.whsbpw.cn",
        "s19.cnzz.com",
        "z8.cnzz.com",
        "s4.cnzz.com",
        "f5w.as12df.top",
        "ae01.alicdn.com",
        "www.92424.cn",
        "k.wudejia.com",
        "vivovip.mmszxc.top",
        "qiu.xixiqiu.com",
        "cdnjs.hnfenxun.com",
        "cms.qdwght.com"
    ]
}