//./jshttp.js
{
"spider":"./top98_1.jar",
"sites" : [
{"key":"drpy","name":"豆瓣🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"豆瓣","name":"豆瓣2🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy_js_豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/drpy2.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/drpy.js"},
{"key":"7喜影院","name":"🛩7喜影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/7喜影院.js"},
{"key":"欧乐影院","name":"🛩歐樂影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧乐影院.js"},
{"key":"独播库","name":"🛩独播库🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/独播库.js"},
{"key":"欧帝影院","name":"🛩欧帝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧帝影院.js"},
{"key":"美视网","name":"🌎美视网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/美视网.js"},
{"key":"起飞影院","name":"🌎起飞影院💬","type":3,"api":"./lib/drpy2.min.js","ext":"./js/起飞影院.js"},
{"key":"大米星球","name":"🌎大米星球(量)🍭♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大米星球.js"},
{"key":"豆芽影院","name":"🌎豆芽影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆芽影院.js"},
{"key":"filter_飞飞影视","name":"飞飞影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/飞飞影视.js"},
{"key":"filter_达达龟","name":"达达龟🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/达达龟.js"},
{"key":"filter_豆巴影视","name":"豆巴影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆巴影视.js"},
{"key":"filter_被窝电影","name":"被窝电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/被窝电影.js"},
{"key":"filter_萌蛋蛋[V2]","name":"萌蛋蛋[V2]🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/萌蛋蛋[V2].js"},
{"key":"filter_苹果DJ","name":"苹果DJ🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/苹果DJ.js"},
{"key":"filter_花猫TV","name":"花猫TV🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/花猫TV.js"},
{"key":"filter_网飞.TV","name":"网飞.TV🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/网飞.TV.js"},
{"key":"filter_纽约影院","name":"纽约影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/纽约影院.js"},
{"key":"filter_米爱影视","name":"米爱影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/米爱影视.js"},
{"key":"filter_秋霞影视","name":"秋霞影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/秋霞影视.js"},
{"key":"filter_看看屋","name":"看看屋🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看看屋.js"},
{"key":"filter_相声随身听","name":"相声随身听🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/相声随身听.js"},
{"key":"filter_皮皮鸭","name":"皮皮鸭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/皮皮鸭.js"},
{"key":"filter_清风DJ","name":"清风DJ🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/清风DJ.js"},
{"key":"filter_朴樱影视","name":"朴樱影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/朴樱影视.js"},
{"key":"filter_星空影视","name":"星空影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/星空影视.js"},
{"key":"filter_新片场","name":"新片场🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/新片场.js"},
{"key":"filter_慢大浪","name":"慢大浪🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/慢大浪.js"},
{"key":"filter_影视之家","name":"影视之家🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影视之家.js"},
{"key":"filter_天空影视[V2]","name":"天空影视[V2]🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/天空影视[V2].js"},
{"key":"filter_创艺影视[V2]","name":"创艺影视[V2]🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/创艺影视[V2].js"},
{"key":"filter_人人","name":"人人🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/人人.js"},
{"key":"filter_二次萌影视","name":"二次萌影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/二次萌影视.js"},
{"key":"filter_UM电影","name":"UM电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/UM电影.js"},
{"key":"filter_HG影院[V2]","name":"HG影院[V2]🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HG影院[V2].js"},
{"key":"filter_FreeOK","name":"FreeOK🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/FreeOK.js"},
{"key":"filter_555影视[V2]","name":"555影视[V2]🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/555影视[V2].js"},
{"key":"filter_345看片","name":"345看片🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/345看片.js"},
{"key":"filter_139影视","name":"139影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/139影视.js"},
{"key":"filter_omofun动漫","name":"omofun动漫🎭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/omofun动漫.js"},
{"key":"filter_i275听书","name":"i275听书🎭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/i275听书.js"},
{"key":"filter_酷狗MV","name":"酷狗MV🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷狗MV.js"},
{"key":"filter_有声听书网","name":"有声听书网🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/有声听书网.js"},
{"key":"filter_开眼视频","name":"开眼视频🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/开眼视频.js"},
{"key":"filter_NyaFun","name":"NyaFun🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/NyaFun.js"},
{"key":"filter_MV263","name":"MV263🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/MV263.js"},
{"key":"filter_JangoIndex","name":"JangoIndex🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JangoIndex.js"},
{"key":"filter_74听书","name":"74听书🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/74听书.js"},
{"key":"filter_粤爱看","name":"🇭🇰粤爱看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/粤爱看.js"}
],
"lives": [
    {
      "name": "直播源",
      "type": 0,
      "url": "./直播源.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },    
    {
      "name": "FongMi",
      "type": 1,
      "url": "https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/live.json",
      "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={epg}&date={date}",
      "logo": "http://epg.51zmt.top:8000/{logo}"
    },
    {
      "name": "台灣",
      "type": 0,
      "url": "./live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
        {
      "name": "直播1",
      "type": 0,
      "url": "http://home.jundie.top:81/Cat/tv/live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
    {
      "name": "直播2",
      "type": 0,
      "url": "https://dashu0754.com/api/v3/file/get/111/%E6%82%9F%E7%A9%BA.txt?sign=Vh_6WlBWzq1GeV88r1QjRQE9DCNcz5rBZpmSMo_q_y8%3D%3A0",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    }
  ],
"rules": [ 
{"host":"*", "rule":["douyinvod.com", "/video/tos/cn/"]}, 
{"host":"*", "rule":["default.365yg.com", "/video/tos/cn/"]}, 
{"host":"*","rule":["ysting.ysxs8.vip","m4a"]},
{"host":"*", "rule":["/m3u8.php?path=", ".m3u8"]}, 
{"host":"*", "rule":["/API.php?time=", "key=", "path=", ".m3u8"]}, 
{"host":"*", "rule":["oss-cn-m3u8", "myqcloud.com.zh188.net", "?url=", ".m3u8"]}, 
{"host":"*", "rule":["iesdouyin.com/aweme", "video_id="]},
{"host":"*", "rule":["douyin.com/aweme", "video_id="]},
{"host":"*", "rule":["huoshan.com", "/item/video/"]}, 
{"host":"*", "rule":["http((?!http).){12,}?\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)\\?.*"]}, 
{"host":"*", "rule":["http((?!http).){12,}\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)"]},
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".m3u8"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mp4"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mkv"]}, 
{"host":"www.007ts.me", "rule":["hls.pchj.net", ".m3u8"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time="]},
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},
{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},
{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]}
],
"parses":[
{"name":"懒懒","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"猫爪","type":0,"url":"https://jx.zhanlangbu.com/?url="},
{"name":"ok","type":0,"url":"https://okjx.cc/?url="},
{"name":"bozrc","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","leshi","LS","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":""}}},
{"name":"不累","type":0,"url":"https://blbfq.f3322.net/player/analysis.php?v=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"cod","type":0,"url":"https://ksksl.codjx.com/?url="},
{"name":"byg解析","type":0,"url":"https://byg.ziqj5.shop/?url="},
{"name":"xmflv","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"365","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"26db","type":0,"url":"http://vip.26db.cn/g/?url="},
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"FreeOK","type":0,"url":"https://play.86516.tk/OKPlayer/?url="},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url="}],
"ads": ["https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd","mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg"
}