//./jshttp(1).js
{
"spider":"./top98_1.jar",
"sites" : [
{"key":"起飞影院","name":"🌎起飞影院💬","type":3,"api":"./lib/drpy2.min.js","ext":"./js/起飞影院.js"},
{"key":"量子资源","name":"🌟量子资源","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"categories":["国产剧","国产动漫","泰国剧","台湾剧","香港剧","欧美剧","韩国剧","日本剧","动漫","体育","剧情片","动作片","爱情片","喜剧片"]},
{"key":"淘片资源网","name":"🌟淘片资源","type":0,"api":"https://taopianapi.com/home/cjapi/as/mc/vod/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"非凡资源网","name":"🌟非凡资源","type":0,"api":"http://cj.ffzyapi.com/api.php/provide/vod/from/ffm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"海外看资源网","name":"🌟海外看资源","type":0,"api":"https://haiwaikan.com/api.php/provide/vod/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"68资源网","name":"🌟68资源","type":0,"api":"https://caiji.68zyapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"優質资源网","name":"🌟優質资源","type":0,"api":"https://api.1080zyku.com/inc/api.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"飛速资源网","name":"🌟飛速资源","type":0,"api":"https://www.feisuzyapi.com/api.php/provide/vod/from/fsm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"魚樂资源网","name":"🌟魚樂资源","type":1,"api":"https://api.ylzy1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鷹资源网","name":"🌟金鷹资源","type":0,"api":"https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"if101","name":"🛩if101","type":3,"api":"./lib/drpy2.min.js","ext":"./js/if101.js"},
{"key":"drpy","name":"豆瓣🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"豆瓣","name":"豆瓣2🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy_js_豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/drpy2.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/drpy.js"},
{"key":"7喜影院","name":"🛩7喜影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/7喜影院(1).js"},
{"key":"多瑙影视","name":"🈵多瑙影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/多瑙影视(1).js"},
{"key":"CK资源","name":"🛩CK资源♒","type":1,"api":"https://ckzy.me/api.php/provide/vod/","playUrl":"","categories":[],"searchable":1,"filterable":1},
{"key":"CK资源(VPN)","name":"🛩CK资源(VPN)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/ck资源.js"},
{"key":"539影院","name":"🌎539影院","type":3,"api":"./lib/drpy2.min.js","ext":"./js/539影院.js"},
{"key":"量子影视","name":"🛩量子影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/量子影视(1).js"},
{"key":"飞兔影视","name":"🛩飞兔影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/飞兔影视(1).js"},
{"key":"欧乐影院","name":"🛩歐樂影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/欧乐影院(1).js"},
{"key":"独播库","name":"🛩独播库🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/独播库.js"},
{"key":"欧帝影院","name":"🛩欧帝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧帝影院.js"},
{"key":"百度资源网","name":"🌟百度资源","type":0,"api":"https://api.apibdzy.com/api.php/provide/vod/from/dbm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"小宝影视","name":"🈵☁小宝影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小宝影视.js"},
{"key":"回响影视","name":"🈵回响影视🔎評分","type":3,"api":"./lib/drpy2.min.js","ext":"./js/回响影视.js"},
{"key":"真不卡","name":"🈵☁真不卡🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/真不卡.js"},
{"key":"gaze","name":"💬gaze🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/gaze.js"},
{"key":"乐鱼影视","name":"💬乐鱼影视(全集)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/乐鱼影视.js"},
{"key":"八蛋影视","name":"💬八蛋影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/八蛋影视.js"},
{"key":"影渣渣","name":"💬影渣渣🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影渣渣.js"},
{"key":"尘落影视","name":"💬尘落影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/尘落影视.js"},
{"key":"追剧喵","name":"💬追剧喵🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧喵.js"},
{"key":"喵喵","name":"💬喵喵♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/喵喵(1).js"},
{"key":"菜狗","name":"💬菜狗🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/菜狗.js"},
{"key":"海兔影院","name":"🛩海兔影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海兔影院.js"},
{"key":"小宝影院","name":"🛩小宝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小宝影院.js"},
{"key":"HoHo影视","name":"🛩HoHo影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HoHo影视.js"},
{"key":"唐人街影视","name":"🛩唐人街影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/唐人街影视.js"},
{"key":"爱壹帆","name":"🛩爱壹帆🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱壹帆.js"},
{"key":"大中影视","name":"🛩大中影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大中影视.js"},
{"key":"金曼影视","name":"🛩金曼影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/金曼影视.js"},
{"key":"泥巴","name":"🛩泥巴🔎","type":3,"api":"csp_Nbys","searchable":1,"filterable":1},
{"key":"大米星球","name":"🌎大米星球(量)🍭♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/大米星球(1).js"},
{"key":"奇优影院","name":"🌎奇优影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/奇优影院(1).js"},
{"key":"追剧啦","name":"🌎追剧啦(TK、CK)♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/追剧啦(1).js"},
{"key":"天天视频","name":"🌎天天视频(CK)♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/天天视频(1).js"},
{"key":"鸭奈飞","name":"🌎鸭奈飞🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/鸭奈飞.js"},
{"key":"歪片星球","name":"歪片星球🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/歪片星球.js"},
{"key":"奇珍异兽","name":"奇珍异兽🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇珍异兽.js"},
{"key":"NFM影视","name":"🌎NFM影视(量子🍭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/NFM影视.js"},
{"key":"艾旦影视","name":"🌎艾旦影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/艾旦影视(1).js"},
{"key":"HG影院[V2]","name":"🌎HG影院[V2](ff)♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/HG影院[V2](1).js"},
{"key":"纽约影院","name":"🌎纽约影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/纽约影院(1).js"},
{"key":"朴樱影视","name":"朴樱影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/朴樱影视(1).js"},
{"key":"星空影视","name":"🌎星空影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/星空影视(1).js"},
{"key":"蛋蛋赞","name":"🌎蛋蛋赞♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/蛋蛋赞(1).js"},
{"key":"蛋蛋魔法","name":"🌎蛋蛋魔法♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/蛋蛋魔法(1).js"},
{"key":"追剧达人","name":"🌎追剧达人♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/追剧达人(1).js"},
{"key":"NY影院","name":"🧡NY影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/NY影院(1).js"},
{"key":"浮生半日","name":"🌎浮生半日♒(TK)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/浮生半日(1).js"},
{"key":"子子影视","name":"子子影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/子子影视(1).js"},
{"key":"我爱跟剧","name":"我爱跟剧♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/我爱跟剧(1).js"},
{"key":"土狗影院","name":"土狗影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/土狗影院(1).js"},
{"key":"小狗影院","name":"小狗影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/小狗影院(1).js"},
{"key":"海外看影院","name":"海外看影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/海外看影院(1).js"},
{"key":"天空影视[V2]","name":"🌎天空影视[V2](ff)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/天空影视[V2].js"},
{"key":"555影视[V2]","name":"☁555影视[V2]🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/555影视[V2].js"},
{"key":"蜥蜴影视","name":"🌎蜥蜴影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蜥蜴影视.js"},	
{"key":"米爱影视","name":"🌎米爱影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/米爱影视.js"},	
{"key":"飞飞影视","name":"☁飞飞影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/飞飞影视.js"},	
{"key":"达达龟","name":"🌎达达龟(量，凡)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/达达龟.js"},	
{"key":"萌蛋蛋[V2]","name":"🌎萌蛋蛋[V2](ff)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/萌蛋蛋[V2].js"},	
{"key":"看片狂人","name":"☁看片狂人","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看片狂人.js"},	
{"key":"美视网","name":"🌎美视网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/美视网.js"},	
{"key":"豆芽影院","name":"🌎豆芽影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆芽影院.js"},	
{"key":"冷曦影视","name":"☁冷曦影视(神马,飞速)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/冷曦影视.js"},	
{"key":"素白白","name":"☁素白白","type":3,"api":"./lib/drpy2.min.js","ext":"./js/素白白.js"},	
{"key":"蚂蚁影视","name":"☁蚂蚁影视(高速云)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蚂蚁影视.js"},	
{"key":"碟调影视","name":"☁碟调影视(淘片,魚樂)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/碟调影视.js"},	
{"key":"稀饭影视","name":"☁稀饭影视(优质,淘片)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/稀饭影视.js"},	
{"key":"溪谷影视","name":"🌎溪谷影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/溪谷影视.js"},	
{"key":"诺讯影视","name":"🌎诺讯影视(溪谷)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/诺讯影视.js"},	
{"key":"1080P","name":"🌎1080P🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/1080P.js"},	
{"key":"楚门影院","name":"🌎楚门影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/楚门影院.js"},	
{"key":"煲剧吧","name":"🌎煲剧吧(量子)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/煲剧吧.js"},	
{"key":"快看","name":"🌎快看(量子)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/快看.js"},	
{"key":"双十电影","name":"🌎双十电影(量子)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/双十电影.js"},	
{"key":"热播库","name":"🌎热播库(量子)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/热播库.js"},	
{"key":"光棍影院","name":"🌎光棍影院(量子)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/光棍影院.js"},	
{"key":"利丽娅电影","name":"🌎利丽娅电影(量子)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/利丽娅电影.js"},	
{"key":"饭团影视","name":"🌎饭团影视(量子)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/饭团影视.js"},	
{"key":"四个圈影视","name":"🌎四个圈影视(金鷹)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/四个圈影视.js"},	
{"key":"cokemv","name":"🌎cokemv🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/cokemv.js"},	
{"key":"叭度影视","name":"🌎叭度影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/叭度影视.js"},	
{"key":"100影院","name":"??100影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/100影院.js"},	
{"key":"l0l","name":"🌎l0l","type":3,"api":"./lib/drpy2.min.js","ext":"./js/l0l.js"},	
{"key":"69美剧","name":"🌎69美剧🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/69美剧.js"},	
{"key":"UM电影","name":"☁UM电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/UM电影.js"},	
{"key":"在线之家Ⅱ","name":"🌎在线之家Ⅱ","type":3,"api":"./lib/drpy2.min.js","ext":"./js/在线之家Ⅱ.js"},	
{"key":"看BZ影视","name":"🌎看BZ影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看BZ影视.js"},	
{"key":"TV蜂","name":"🌎TV蜂","type":3,"api":"./lib/drpy2.min.js","ext":"./js/TV蜂.js"},	
{"key":"凌云影视","name":"☁凌云影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/凌云影视.js"},	
{"key":"创艺影视","name":"☁创艺影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/创艺影视.js"},	
{"key":"看了么","name":"☁看了么(智库)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看了么.js"},	
{"key":"大师兄影视","name":"🌎大师兄影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大师兄影视.js"},	
{"key":"孜然影视","name":"🌎孜然影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/孜然影视.js"},	
{"key":"9U电影","name":"🌎9U电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/9U电影.js"},	
{"key":"Nike影视","name":"🌎Nike影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Nike影视.js"},	
{"key":"七年影视","name":"☁七年影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/七年影视.js"},	
{"key":"星辰","name":"🌎星辰","type":3,"api":"./lib/drpy2.min.js","ext":"./js/星辰.js"},	
{"key":"人人影视","name":"🌎人人影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/人人影视.js"},	
{"key":"8号影院","name":"🌎8号影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/8号影院.js"},	
{"key":"孜然影视","name":"🌎孜然影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/孜然影视.js"},	
{"key":"被窝电影","name":"☁被窝电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/被窝电影.js"},	
{"key":"秋霞影视","name":"☁秋霞影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/秋霞影视.js"},	
{"key":"看看屋","name":"🌎看看屋🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看看屋.js"},	
{"key":"慢大浪","name":"☁慢大浪🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/慢大浪.js"},	
{"key":"影视之家","name":"🌎影视之家🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影视之家.js"},	
{"key":"二次萌影视","name":"🌎二次萌影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/二次萌影视.js"},	
{"key":"FreeOK","name":"☁FreeOK🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/FreeOK.js"},	
{"key":"345看片","name":"☁345看片🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/345看片.js"},	
{"key":"139影视","name":"☁139影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/139影视.js"},	
{"key":"UrleBird","name":"🛤TikTok镜像","type":3,"api":"./lib/drpy2.min.js","ext":"./js/UrleBird.js"},
{"key":"JustLive","name":"🛤JustLive🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JustLive.js"},
{"key":"短视频","name":"🛤短视频","type":3,"api":"./lib/drpy2.min.js","ext":"./js/短视频.js"},
{"key":"斗鱼直播","name":"🛤斗鱼直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/斗鱼直播.js"},
{"key":"虎牙直播","name":"🛤虎牙直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/虎牙直播.js"},
{"key":"哔哩直播","name":"🛤哔哩直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩直播.js"},
{"key":"哔哩影视","name":"🛤哔哩影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩影视.js"},
{"key":"JRKAN直播","name":"🛤JRKAN直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JRKAN直播.js"},
{"key":"310直播","name":"🛤310直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/310直播.js"},
{"key":"drpy_js_360影视","name":"官源🏛360","type":3,"api":"./lib/drpy2.min.js","ext":"./js/360影视.js"},
{"key":"drpy_js_奇珍异兽","name":"官源🏛爱奇艺🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇珍异兽.js"},
{"key":"drpy_js_优酷","name":"官源🏛优酷🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/优酷.js"},
{"key":"drpy_js_腾云驾雾","name":"官源🏛腾讯🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/腾云驾雾.js"},
{"key":"drpy_js_百忙无果","name":"官源🏛芒果🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/百忙无果.js"},
{"key":"drpy_js_菜狗","name":"官源🏛搜狗🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/菜狗.js"},
{"key":"小品网","name":"🎵小品网","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小品网.js"},
{"key":"幻听网听书","name":"🎵幻听网听书","type":3,"api":"./lib/drpy2.min.js","ext":"./js/幻听网听书.js"},
{"key":"喜马拉雅","name":"🎵喜马拉雅","type":3,"api":"./lib/drpy2.min.js","ext":"./js/喜马拉雅.js"},
{"key":"海盗听书","name":"🎵海盗听书","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海盗听书.js"},
{"key":"爱车MV","name":"🎵爱车MV","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱车MV.js"},
{"key":"酷奇MV","name":"🎵酷奇MV","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷奇MV.js"},
{"key":"音乐演唱","name":"🎵音乐演唱","type":3,"api":"csp_Bili","ext":"./js/音乐演唱.json","jar":"./fm.jar"},
{"key":"奇米动漫","name":"🎭奇米动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇米动漫.js"},
{"key":"怡萱动漫","name":"🎭怡萱动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/怡萱动漫.js"},
{"key":"妮可动漫","name":"🎭妮可动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/妮可动漫.js"},
{"key":"AGE动漫","name":"🎭AGE动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/AGE动漫.js"},
{"key":"动漫岛","name":"🎭动漫岛🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/动漫岛.js"},
{"key":"gaze-","name":"🎭gaze🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/gaze.js"},
{"key":"NT动漫","name":"🎭NT动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/NT动漫.js"},
{"key":"异世界动漫","name":"🎭异世界动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/异世界动漫.js"},
{"key":"曲奇动漫","name":"🎭曲奇动漫","type":3,"api":"./lib/drpy2.min.js","ext":"./js/曲奇动漫.js"},
{"key":"omofun动漫","name":"omofun动漫🎭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/omofun动漫.js"},
{"key":"i275听书","name":"i275听书🎭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/i275听书.js"},
{"key":"酷狗MV","name":"酷狗MV🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷狗MV.js"},
{"key":"有声听书网","name":"有声听书网🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/有声听书网.js"},
{"key":"开眼视频","name":"开眼视频🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/开眼视频.js"},
{"key":"NyaFun","name":"NyaFun🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/NyaFun.js"},
{"key":"MV263","name":"MV263🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/MV263.js"},
{"key":"JangoIndex","name":"JangoIndex🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JangoIndex.js"},
{"key":"74听书","name":"74听书🎭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/74听书.js"},
{"key":"KUBO影视","name":"🇹🇼KUBO(繁體)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/KUBO影视.js"},
{"key":"映迷影院","name":"🇹🇼映迷(繁體)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/映迷影院.js"},
{"key":"剧迷","name":"🇹🇼剧迷(繁體)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/剧迷.js"},
{"key":"楓林網","name":"🇹🇼楓林網(繁體)♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/楓林網(1).js"},
{"key":"粤爱看","name":"🇭🇰粤爱看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/粤爱看.js"}
],
"lives": [
    {
      "name": "直播源",
      "type": 0,
      "url": "./直播源(1).txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },    
    {
      "name": "FongMi",
      "type": 1,
      "url": "https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/live.json",
      "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={epg}&date={date}",
      "logo": "http://epg.51zmt.top:8000/{logo}"
    },
    {
      "name": "台灣",
      "type": 0,
      "url": "./live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
        {
      "name": "直播1",
      "type": 0,
      "url": "http://home.jundie.top:81/Cat/tv/live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
    {
      "name": "直播2",
      "type": 0,
      "url": "https://dashu0754.com/api/v3/file/get/111/%E6%82%9F%E7%A9%BA.txt?sign=Vh_6WlBWzq1GeV88r1QjRQE9DCNcz5rBZpmSMo_q_y8%3D%3A0",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    }
  ],
"rules": [ 
{"host":"*", "rule":["douyinvod.com", "/video/tos/cn/"]}, 
{"host":"*", "rule":["default.365yg.com", "/video/tos/cn/"]}, 
{"host":"*","rule":["ysting.ysxs8.vip","m4a"]},
{"host":"*", "rule":["/m3u8.php?path=", ".m3u8"]}, 
{"host":"*", "rule":["/API.php?time=", "key=", "path=", ".m3u8"]}, 
{"host":"*", "rule":["oss-cn-m3u8", "myqcloud.com.zh188.net", "?url=", ".m3u8"]}, 
{"host":"*", "rule":["iesdouyin.com/aweme", "video_id="]},
{"host":"*", "rule":["douyin.com/aweme", "video_id="]},
{"host":"*", "rule":["huoshan.com", "/item/video/"]}, 
{"host":"*", "rule":["http((?!http).){12,}?\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)\\?.*"]}, 
{"host":"*", "rule":["http((?!http).){12,}\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)"]},
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".m3u8"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mp4"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mkv"]}, 
{"host":"www.007ts.me", "rule":["hls.pchj.net", ".m3u8"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time="]},
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},
{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},
{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]}
],
"parses":[
{"name":"懒懒","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"猫爪","type":0,"url":"https://jx.zhanlangbu.com/?url="},
{"name":"ok","type":0,"url":"https://okjx.cc/?url="},
{"name":"bozrc","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","leshi","LS","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":""}}},
{"name":"不累","type":0,"url":"https://blbfq.f3322.net/player/analysis.php?v=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"cod","type":0,"url":"https://ksksl.codjx.com/?url="},
{"name":"byg解析","type":0,"url":"https://byg.ziqj5.shop/?url="},
{"name":"xmflv","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"365","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"26db","type":0,"url":"http://vip.26db.cn/g/?url="},
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"FreeOK","type":0,"url":"https://play.86516.tk/OKPlayer/?url="},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url="}],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg",
    "ads": [
        "vip.ffzyad.com",
        "iqiyi.hbuioo.com",
        "https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd",
        "mimg.0c1q0l.cn",
        "www.googletagmanager.com",
        "www.google-analytics.com",
        "mc.usihnbcq.cn",
        "mg.g1mm3d.cn",
        "mscs.svaeuzh.cn",
        "cnzz.hhttm.top",
        "tp.vinuxhome.com",
        "cnzz.mmstat.com",
        "www.baihuillq.com",
        "s23.cnzz.com",
        "z3.cnzz.com",
        "c.cnzz.com",
        "stj.v1vo.top",
        "z12.cnzz.com",
        "img.mosflower.cn",
        "tips.gamevvip.com",
        "ehwe.yhdtns.com",
        "xdn.cqqc3.com",
        "www.jixunkyy.cn",
        "sp.chemacid.cn",
        "hm.baidu.com",
        "s9.cnzz.com",
        "z6.cnzz.com",
        "um.cavuc.com",
        "mav.mavuz.com",
        "wofwk.aoidf3.com",
        "z5.cnzz.com",
        "xc.hubeijieshikj.cn",
        "tj.tianwenhu.com",
        "xg.gars57.cn",
        "k.jinxiuzhilv.com",
        "cdn.bootcss.com",
        "ppl.xunzhuo123.com",
        "xomk.jiangjunmh.top",
        "img.xunzhuo123.com",
        "z1.cnzz.com",
        "s13.cnzz.com",
        "xg.huataisangao.cn",
        "z7.cnzz.com",
        "xg.huataisangao.cn",
        "z2.cnzz.com",
        "s96.cnzz.com",
        "q11.cnzz.com",
        "thy.dacedsfa.cn",
        "xg.whsbpw.cn",
        "s19.cnzz.com",
        "z8.cnzz.com",
        "s4.cnzz.com",
        "f5w.as12df.top",
        "ae01.alicdn.com",
        "www.92424.cn",
        "k.wudejia.com",
        "vivovip.mmszxc.top",
        "qiu.xixiqiu.com",
        "cdnjs.hnfenxun.com",
        "cms.qdwght.com"
    ]
}